#############################################################################
# Makefile for building: Gomoku.app/Contents/MacOS/Gomoku
# Generated by qmake (2.01a) (Qt 4.7.0) on: dim. mai 29 14:43:30 2011
# Project:  Gomoku.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.7/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Applications/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile Gomoku.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.7/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -Iinc -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -L/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -F/tmp/qt-stuff-6474/source/qt-everywhere-opensource-src-4.7.0/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/APlayer.cpp \
		src/Board.cpp \
		src/Game.cpp \
		src/HPlayer.cpp \
		src/mainwindow.cpp \
		src/Referee.cpp \
		src/Square.cpp \
		src/gridmanager.cpp \
		src/parameters.cpp moc_mainwindow.cpp \
		moc_Game.cpp \
		moc_parameters.cpp \
		qrc_texture.cpp
OBJECTS       = main.o \
		APlayer.o \
		Board.o \
		Game.o \
		HPlayer.o \
		mainwindow.o \
		Referee.o \
		Square.o \
		gridmanager.o \
		parameters.o \
		moc_mainwindow.o \
		moc_Game.o \
		moc_parameters.o \
		qrc_texture.o
DIST          = /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		Gomoku.pro
QMAKE_TARGET  = Gomoku
DESTDIR       = 
TARGET        = Gomoku.app/Contents/MacOS/Gomoku

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Gomoku.app/Contents/PkgInfo Gomoku.app/Contents/Resources/empty.lproj Gomoku.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_parameters.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Gomoku.app/Contents/MacOS/ || $(MKDIR) Gomoku.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gomoku.pro  /usr/local/Qt4.7/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.7/mkspecs/common/unix.conf \
		/usr/local/Qt4.7/mkspecs/common/mac.conf \
		/usr/local/Qt4.7/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.7/mkspecs/qconfig.pri \
		/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.7/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.7/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.7/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.7/mkspecs/features/debug.prf \
		/usr/local/Qt4.7/mkspecs/features/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.7/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.7/mkspecs/features/qt.prf \
		/usr/local/Qt4.7/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.7/mkspecs/features/moc.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.7/mkspecs/features/resources.prf \
		/usr/local/Qt4.7/mkspecs/features/uic.prf \
		/usr/local/Qt4.7/mkspecs/features/yacc.prf \
		/usr/local/Qt4.7/mkspecs/features/lex.prf \
		/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Applications/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile Gomoku.pro
/usr/local/Qt4.7/mkspecs/common/unix.conf:
/usr/local/Qt4.7/mkspecs/common/mac.conf:
/usr/local/Qt4.7/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.7/mkspecs/qconfig.pri:
/usr/local/Qt4.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.7/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.7/mkspecs/features/qt_config.prf:
/usr/local/Qt4.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.7/mkspecs/features/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.7/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.7/mkspecs/features/debug.prf:
/usr/local/Qt4.7/mkspecs/features/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.7/mkspecs/features/warn_on.prf:
/usr/local/Qt4.7/mkspecs/features/qt.prf:
/usr/local/Qt4.7/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.7/mkspecs/features/moc.prf:
/usr/local/Qt4.7/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.7/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.7/mkspecs/features/resources.prf:
/usr/local/Qt4.7/mkspecs/features/uic.prf:
/usr/local/Qt4.7/mkspecs/features/yacc.prf:
/usr/local/Qt4.7/mkspecs/features/lex.prf:
/usr/local/Qt4.7/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.7/mkspecs/macx-g++ QMLJSDEBUGGER_PATH=/Applications/Qt/Qt\ Creator.app/Contents/Resources/qml/qmljsdebugger -o Makefile Gomoku.pro

Gomoku.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Gomoku.app/Contents || $(MKDIR) Gomoku.app/Contents 
	@$(DEL_FILE) Gomoku.app/Contents/PkgInfo
	@echo "APPL????" >Gomoku.app/Contents/PkgInfo
Gomoku.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Gomoku.app/Contents/Resources || $(MKDIR) Gomoku.app/Contents/Resources 
	@touch Gomoku.app/Contents/Resources/empty.lproj
	
Gomoku.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Gomoku.app/Contents || $(MKDIR) Gomoku.app/Contents 
	@$(DEL_FILE) Gomoku.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Gomoku,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.7/mkspecs/macx-g++/Info.plist.app >Gomoku.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Gomoku1.0.0 || $(MKDIR) .tmp/Gomoku1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents inc/mainwindow.hpp inc/Types.hpp inc/Square.hpp inc/Referee.hpp inc/HPlayer.hpp inc/gridmanager.hpp inc/Game.hpp inc/Board.hpp inc/APlayer.hpp inc/parameters.hpp .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents ressources/texture.qrc .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/APlayer.cpp src/Board.cpp src/Game.cpp src/HPlayer.cpp src/mainwindow.cpp src/Referee.cpp src/Square.cpp src/gridmanager.cpp src/parameters.cpp .tmp/Gomoku1.0.0/ && $(COPY_FILE) --parents forms/mainwindow.ui forms/parameters.ui .tmp/Gomoku1.0.0/ && (cd `dirname .tmp/Gomoku1.0.0` && $(TAR) Gomoku1.0.0.tar Gomoku1.0.0 && $(COMPRESS) Gomoku1.0.0.tar) && $(MOVE) `dirname .tmp/Gomoku1.0.0`/Gomoku1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gomoku1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Gomoku.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_Game.cpp moc_parameters.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_Game.cpp moc_parameters.cpp
moc_mainwindow.cpp: inc/Game.hpp \
		inc/Referee.hpp \
		inc/Board.hpp \
		inc/Square.hpp \
		inc/Types.hpp \
		inc/APlayer.hpp \
		inc/parameters.hpp \
		inc/mainwindow.hpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/mainwindow.hpp -o moc_mainwindow.cpp

moc_Game.cpp: inc/Referee.hpp \
		inc/Board.hpp \
		inc/Square.hpp \
		inc/Types.hpp \
		inc/APlayer.hpp \
		inc/Game.hpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/Game.hpp -o moc_Game.cpp

moc_parameters.cpp: inc/parameters.hpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/parameters.hpp -o moc_parameters.cpp

compiler_rcc_make_all: qrc_texture.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_texture.cpp
qrc_texture.cpp: ressources/texture.qrc \
		ressources/gazon.jpg \
		ressources/parquet.jpg
	/Developer/Tools/Qt/rcc -name texture ressources/texture.qrc -o qrc_texture.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_parameters.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_parameters.h
ui_mainwindow.h: forms/mainwindow.ui
	/Developer/Tools/Qt/uic forms/mainwindow.ui -o ui_mainwindow.h

ui_parameters.h: forms/parameters.ui
	/Developer/Tools/Qt/uic forms/parameters.ui -o ui_parameters.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

APlayer.o: src/APlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o APlayer.o src/APlayer.cpp

Board.o: src/Board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o src/Board.cpp

Game.o: src/Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o src/Game.cpp

HPlayer.o: src/HPlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HPlayer.o src/HPlayer.cpp

mainwindow.o: src/mainwindow.cpp ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

Referee.o: src/Referee.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Referee.o src/Referee.cpp

Square.o: src/Square.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Square.o src/Square.cpp

gridmanager.o: src/gridmanager.cpp inc/gridmanager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridmanager.o src/gridmanager.cpp

parameters.o: src/parameters.cpp inc/parameters.hpp \
		ui_parameters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameters.o src/parameters.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_Game.o: moc_Game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Game.o moc_Game.cpp

moc_parameters.o: moc_parameters.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameters.o moc_parameters.cpp

qrc_texture.o: qrc_texture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_texture.o qrc_texture.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

